import { HeaderSearchPage } from '@/components/Headers';
import '../globals.css';

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
};

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <HeaderSearchPage />
      {children}
    </div>
  );
}
